# Project-wide Gradle settings.

# AndroidX libraries are a replacement for the older Support libraries.
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enables copy-paced-of-build-cache for faster builds
org.gradle.caching=true
